apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sbombastic.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sbombastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      {{ include "sbombastic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  replicas: {{ .Values.controller.replicas }}
  template:
    metadata:
      labels:
        {{ include "sbombastic.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      containers:
        - command:
            - /controller
          args:
            - -leader-elect
            - -health-probe-bind-address=:8081
            - -nats-url
            - {{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222
            {{- if .Values.controller.logLevel }}
            - -log-level={{ .Values.controller.logLevel }}
            {{- end }}
          image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          name: controller
          securityContext:
            {{ include "sbombastic.securityContext" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - mountPath: "/nats/tls"
              name: nats-tls
              readOnly: true
      volumes:
        - name: nats-tls
          secret:
            secretName: {{ include "sbombastic.fullname" . }}-nats-controller-client-tls
      serviceAccountName: {{ include "sbombastic.fullname" . }}-controller
      terminationGracePeriodSeconds: 10
