---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{ include "sbombastic.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "sbombastic.fullname" . }}-controller
rules:
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries
  - scanjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries/finalizers
  - scanjobs/finalizers
  verbs:
  - update
- apiGroups:
  - sbombastic.rancher.io
  resources:
  - registries/status
  - scanjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.sbombastic.rancher.io
  resources:
  - images
  - sboms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.sbombastic.rancher.io
  resources:
  - images/finalizers
  - sboms/finalizers
  verbs:
  - update
- apiGroups:
  - storage.sbombastic.rancher.io
  resources:
  - images/status
  - sboms/status
  verbs:
  - get
  - patch
  - update
